apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: React Web Boilerplate
  annotations:
    github.com/project-slug: daviddykeuk/create-react-app-ts-sb
spec:
  type: service
  lifecycle: production
  owner: onboarding
